title: Jee-weon Jung
url: "https://jungjee.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Designed by Ankit Sultana, adapted by Jee-weon Jung."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "./"
 - name: "Resume"
   link: "CV_Jee-weon_Jung_20220703.pdf"
 - name: "GitHub"
   link: "https://github.com/Jungjee"
 - name: "Contact"
   link: "contact"
