title: Jee-weon Jung
url: "https://jungjee.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://jungjee.com"
footer_text: "Designed by Ankit Sultana, adapted by Jee-weon Jung."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "./"
 - name: "CV"
   link: "CV_Jee-weon_Jung.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Resource"
   link: "resource"
- name: "Mentoring"
   link: "mentoring"
